#!/bin/bash

# 🔒 Durusuna Mobile - Secure Development Configuration Script
# This script helps configure environment variables for development

echo "🔒 Durusuna Mobile - Secure Development Setup"
echo "=============================================="

# Get local IP address automatically
LOCAL_IP=$(ifconfig en0 2>/dev/null | grep "inet " | awk '{print $2}' | head -1)
if [ -z "$LOCAL_IP" ]; then
    LOCAL_IP=$(ifconfig | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}' | head -1)
fi

echo "📱 Detected local IP: $LOCAL_IP"
echo ""

# Ask user for configuration
read -p "🔧 Are you testing on a physical device? (y/n): " USE_DEVICE
read -p "🌐 Backend port (default: 3001): " PORT
PORT=${PORT:-3001}

# Set environment for this session
if [ "$USE_DEVICE" = "y" ] || [ "$USE_DEVICE" = "Y" ]; then
    export USE_PHYSICAL_DEVICE=true
    export DEV_SERVER_IP=$LOCAL_IP
    echo "✅ Configured for physical device testing"
    echo "📱 Device should connect to: http://$LOCAL_IP:$PORT"
else
    export USE_PHYSICAL_DEVICE=false
    echo "✅ Configured for emulator/simulator testing"
fi

export DEV_SERVER_PORT=$PORT
export ENVIRONMENT=development
export DEBUG_MODE=true

echo ""
echo "🔐 Environment Variables Set:"
echo "   ENVIRONMENT=$ENVIRONMENT"
echo "   USE_PHYSICAL_DEVICE=$USE_PHYSICAL_DEVICE"
echo "   DEV_SERVER_IP=$DEV_SERVER_IP"
echo "   DEV_SERVER_PORT=$DEV_SERVER_PORT"
echo "   DEBUG_MODE=$DEBUG_MODE"
echo ""

# Create a temporary env file for this session
cat > .env.local << EOF
# Generated by configure_dev.sh - DO NOT COMMIT TO GIT
ENVIRONMENT=development
USE_PHYSICAL_DEVICE=$USE_PHYSICAL_DEVICE
DEV_SERVER_IP=$DEV_SERVER_IP
DEV_SERVER_PORT=$PORT
DEBUG_MODE=true
EOF

echo "📄 Created .env.local (this file is gitignored)"
echo ""

# Flutter build commands
echo "🚀 Run your app with:"
if [ "$USE_DEVICE" = "y" ] || [ "$USE_DEVICE" = "Y" ]; then
    echo "   flutter run --dart-define=USE_PHYSICAL_DEVICE=true --dart-define=DEV_SERVER_IP=$LOCAL_IP --dart-define=DEV_SERVER_PORT=$PORT"
else
    echo "   flutter run --dart-define=USE_PHYSICAL_DEVICE=false --dart-define=DEV_SERVER_PORT=$PORT"
fi
echo ""

# Security reminder
echo "⚠️  SECURITY REMINDER:"
echo "   - Never commit .env.local to git"
echo "   - Don't share your local IP publicly"
echo "   - Use different configs for different environments"
echo "" 